better doc build

diff --git a/{{cookiecutter.out_dir}}/.gitlab-ci.yml b/{{cookiecutter.out_dir}}/.gitlab-ci.yml
--- a/{{cookiecutter.out_dir}}/.gitlab-ci.yml
+++ b/{{cookiecutter.out_dir}}/.gitlab-ci.yml
@@ -89,7 +89,7 @@ variables:
   CURRENT_DOCKER_IMAGE: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:build-${CI_PIPELINE_IID}"
   FORCED_DOCKER_IMAGE:     "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:forced${CI_COMMIT_REF_NAME}"
   REF_DOCKER_IMAGE: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}"
-  LATEST_BRANCH: master
+  MAIN_BRANCH: master
   LATEST_DOCKER_IMAGE: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest"
 {%if not cookiecutter.remove_varnish%}
   # varnish tags
@@ -129,6 +129,7 @@ variables:
   LINT_STATUS_FLAG:         /cache/$CI_PROJECT_PATH_SLUG/w/${CI_PIPELINE_IID}/status_flags_lint
   RELEASE_STATUS_FLAG:      /cache/$CI_PROJECT_PATH_SLUG/w/${CI_PIPELINE_IID}/status_flags_release
   PIPELINE_FLAG:            /cache/$CI_PROJECT_PATH_SLUG/w/${CI_PIPELINE_IID}/status_flags_pipeline
+  COMPOSE_HTTP_TIMEOUT:  "1800"
   BEFORE_STATUS_TIMEOUT: "900"
   AFTER_STATUS_TIMEOUT: "1800"
   PRELOAD_BUILDCACHE_IMAGES: $BUILDCACHE_DOCKER_IMAGE_DOCS $BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS ${BUILDCACHE_REF_DOCKER_IMAGE}-nosquash $BUILDCACHE_CURRENT_DOCKER_IMAGE $BUILDCACHE_REF_DOCKER_IMAGE $BUILDCACHE_LATEST_DOCKER_IMAGE{% if not cookiecutter.remove_varnish %} $LATEST_DOCKER_IMAGE_VARNISH $REF_DOCKER_IMAGE_VARNISH{%endif%}
@@ -136,7 +137,6 @@ variables:
   CACHEABLE_BUILD_BRANCH: ".*"
   TAGGUABLE_IMAGE_BRANCH: "^(master|dev|qa|staging|preprod|prod)$"
   SKIP_TEST_BRANCHES: "(qa|staging|preprod|prod)"
-  MASTER_BRANCH: master
   CACHE_DAYS: "7"
   STATICS_FOLDERS: "{{cookiecutter.statics_folders}}"
   DOCS_FOLDERS: "{{cookiecutter.docs_folders}}"
@@ -193,7 +193,7 @@ before_script: &top_before_script
     if !( update-ca-certificates --help >/dev/null 2>&1 );then
       apk add --no-cache ca-certificates
     fi
-    ( cp -v ${REGISTRY_ROOTDIRECTORY}/ssl/*ca*crt /usr/local/share/ca-certificates || true )
+    ( cp -v ${WORKSPACE}/*ca*crt /usr/local/share/ca-certificates || true )
     update-ca-certificates
    }
    log() { echo "$@">&2; }
@@ -284,7 +284,6 @@ before_script: &top_before_script
     -e "s/^([^=]+_IMAGE_VERSION=.*)latest/\\1build-${CI_PIPELINE_IID}/g" \
     -e "s|$DOCKER_REGISTRY|$BUILDCACHE_REGISTRY|g"                       \
     -e "s/^(CI_COMMIT_SHA=).*/\\1${CI_COMMIT_SHA}/g" > $env;done;
-    for i in SHELL_DEBUG SDEBUG NO_STARTUP_LOGS NO_SILENT;do eval printf "$i=\${$i-}\\\n">>.env;done
 - &warm_statics_tarball
   sh -ec "for t in \"\${STATICS_TARBALL}\" \"\${DOCS_TARBALL}\";do
   if [ -n ${STATICS_LOAD-} ] && [ -e \"\$t\" ];then
@@ -350,6 +349,11 @@ services: &services
       echo "subjectAltName=DNS:${cn}"|openssl x509 -req -extfile /dev/stdin -in "${s}/${cn}.c.csr" -CA "${s}/${cn}.ca.crt" -CAkey "${s}/${cn}.ca.key" \
         -CAcreateserial -out "${s}/${cn}.c.crt" -days 34675 -sha256
     fi
+    for i in ${WORKSPACE} /usr/local/share/ca-certificates;do
+      if [ ! -e "${i}" ];then mkdir -pv "${i}";fi
+      cp -fv "${REGISTRY_ROOTDIRECTORY}"/ssl/*ca*crt "${i}"
+    done
+    ( update-ca-certificates || true )
     ( unset REGISTRY_AUTH_HTPASSWD_REALM REGISTRY_AUTH_HTPASSWD_PATH \
       && export REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY="${PROXYCACHE_ROOTDIRECTORY}" \
       && export REGISTRY_HTTP_ADDR=":${PROXYCACHE_REGISTRY//*:}"  \
@@ -378,7 +382,7 @@ services: &services
   allow_failure: true
   stage: manual_jobs
   when: manual
-  only: [{{mastertagsenvstrs}}]
+  only: ["$TAGGUABLE_IMAGE_BRANCH"]
   except: []
 
 {{staticscomment}}cleanup_all_expired_build_artefacts_from_cache:
@@ -534,7 +538,7 @@ services_tower: &services_tower
 {{docscomment}}      vv docker tag ${BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS} ${BUILDCACHE_DOCKER_IMAGE_DOCS}
 {{docscomment}}      vv docker tag ${BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS} ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
 {{docscomment}}      ( echo $CI_COMMIT_REF_NAME | egrep -q "$TAGGUABLE_IMAGE_BRANCH" ) && vv docker push ${BUILDCACHE_DOCKER_IMAGE_DOCS}
-{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | egrep -q "^$MASTER_BRANCH$") && vv docker push ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
+{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | egrep -q "^$MAIN_BRANCH$") && vv docker push ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
 {{docscomment}}  - &docs_build ./docs/build.sh
 {{docscomment}}  - &docs_save tar czf "${DOCS_TARBALL}" ${DOCS_FOLDERS}
 {{docscomment}}  - *writeokstatus
@@ -599,10 +603,12 @@ build_images: &build_images
       log "$(cat ${dcoverrides})"
       if ( vv $dc build --build-arg BUILDKIT_INLINE_CACHE=1 ${service} ) ;then
         vv docker inspect ${cimg} >/dev/null 2>&1||die "failed building ${cimg}"
+      else
+        exit 1
       fi
     }
     wdc_build() {
-      if !(dc_build "$@");then echo "BUILD ERROR(${cfgs}): ${service}" > /docker_image_errors;fi
+      if ! ( dc_build "$@"; );then echo "BUILD ERROR(${service}): ${@}" > /docker_image_errors;fi
     }
     for service in $DOCKER_BUILT_SERVICES;do
       vv wdc_build ${COMPOSE_PROD_CONFIGS}
@@ -676,7 +682,7 @@ build_images: &build_images
     EOF
     fi
     #
-    if [ "x${CI_COMMIT_REF_NAME}" = "x${LATEST_BRANCH}" ];then cat>>${f}<<EOF
+    if [ "x${CI_COMMIT_REF_NAME}" = "x${MAIN_BRANCH}" ];then cat>>${f}<<EOF
 {%- if not cookiecutter.remove_varnish%}
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE_VARNISH}-dev ${BUILDCACHE_LATEST_DOCKER_IMAGE_VARNISH}-dev
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE_VARNISH}     ${BUILDCACHE_LATEST_DOCKER_IMAGE_VARNISH}
@@ -696,7 +702,7 @@ build_images: &build_images
     EOF
     fi
     #
-    if [ "x${CI_COMMIT_REF_NAME}" = "x${LATEST_BRANCH}" ];then cat>>${f}<<EOF
+    if [ "x${CI_COMMIT_REF_NAME}" = "x${MAIN_BRANCH}" ];then cat>>${f}<<EOF
 {%- if not cookiecutter.remove_varnish%}
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE_VARNISH}-dev ${LATEST_DOCKER_IMAGE_VARNISH}-dev
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE_VARNISH}     ${LATEST_DOCKER_IMAGE_VARNISH}
